### ISSUE TITLE
Document Data.py's Structure

### ISSUE THREAD

**Issue by thompcd** [supermitch/Chinese-Postman#4]
Trying to understand the defined data class is a little confusing. I believe it is a vector definition (point1, point2, magnitude) but cannot find anything about it anywhere to confirm. Can add it to the readme or create a wiki page to link back to the readme? Definitely comments needed in code.

**Comment by supermitch** [comment]
I agree, since I can't read my own code at this point. It's good I've taken a break from it. I'll make some efforts to make things more straightforward. Please feel free to submit pull requests.

**Comment by supermitch** [comment]
Added documentation to data.py docstring, and to README.

**Comment by supermitch** [comment]
Added a tiny 2 comments to network.py and additional info in the README. Closing this issue as done.
