### ISSUE TITLE
I can not for the life of me get this to run

### ISSUE THREAD

**Issue by EliasT05** [supermitch/Chinese-Postman#7]
I am probably just being stupid as I am a bit of a noob but when i try to run main.py it just says invalid graph name and list graph names. How can i change what graph it runs? 
I also wanted to try my own map but i was a bit confused, it says in README.md that it is in the format (start node, end node, length) so that means you should give each intersections a number right

Sorry if this is realy obvious and i am just being stupid but I have tried for multiple hours
Thanks in advance for help

**Comment by jhollowed** [comment]
It runs for me. Are you doing e.g. `python main.py north`? One command line arg is expected

**Comment by supermitch** [comment]
@EliasT05 extremely sorry for not seeing your comment. I only just saw @jhollowed's reply.

Make sure your new graph file is in the `data` folder, and that you're running the script from the root of the repo. The file https://github.com/supermitch/Chinese-Postman/blob/master/data/data.py describes (maybe poorly) how to define the edges of your graph:

`* Edges are defined as (start, end, length)`

So yes, each intersection (called a "node") is numbered. Then a tuple like `(3, 5, 7)` would define an edge from node 3 to node 5, of length 7.
